jobs:
- job: Windows
  pool:
    vmImage: VS2017-Win2016
  steps:
  - template: azure-pipelines-build.yml

# Linux fails to build wxpython. Unsure of best practice for including Python development headers.
#- job: Linux
#  pool:
#    vmImage: 'Ubuntu-16.04'
#  steps:
#  - template: azure-pipelines-build.yml

- job: macOS
  pool:
    vmImage: macOS 10.13
  steps:
  - template: azure-pipelines-build.yml
